<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Tickets Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #ffc107;
            padding-bottom: 15px;
        }
        .header h1 {
            color: #ffc107;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .meta-info {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .meta-info table {
            width: 100%;
        }
        .meta-info td {
            padding: 5px;
            border: none;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
            font-size: 10px;
        }
        th {
            background-color: #ffc107;
            color: #000;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-open { color: #007bff; font-weight: bold; }
        .status-in_progress { color: #ffc107; font-weight: bold; }
        .status-closed { color: #28a745; font-weight: bold; }
        .status-on_hold { color: #6c757d; font-weight: bold; }
        
        .priority-low { color: #6c757d; }
        .priority-medium { color: #17a2b8; }
        .priority-high { color: #ffc107; }
        .priority-critical { color: #dc3545; font-weight: bold; }
        
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }
        .no-data {
            text-align: center;
            padding: 40px;
            color: #666;
            font-style: italic;
        }
        .description {
            max-width: 200px;
            word-wrap: break-word;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Tickets Report</h1>
        <p>ClientConnect CRM - Ticket Management System</p>
        <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td><strong>Total Tickets:</strong></td>
                <td>{{ $tickets->count() }}</td>
                <td><strong>Report Type:</strong></td>
                <td>PDF Export</td>
            </tr>
            <tr>
                <td><strong>Generated By:</strong></td>
                <td>{{ auth()->user()->name }}</td>
                <td><strong>Date Range:</strong></td>
                <td>
                    @if(request('date_from') || request('date_to'))
                        {{ request('date_from') ? \Carbon\Carbon::parse(request('date_from'))->format('M j, Y') : 'Beginning' }}
                        to
                        {{ request('date_to') ? \Carbon\Carbon::parse(request('date_to'))->format('M j, Y') : 'Present' }}
                    @else
                        All Time
                    @endif
                </td>
            </tr>
            <tr>
                <td><strong>Status Filter:</strong></td>
                <td>{{ request('status') ? ucfirst(str_replace('_', ' ', request('status'))) : 'All Statuses' }}</td>
                <td><strong>Priority Filter:</strong></td>
                <td>{{ request('priority') ? ucfirst(request('priority')) : 'All Priorities' }}</td>
            </tr>
        </table>
    </div>

    @if($tickets->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Customer</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Priority</th>
                    <th>Assigned To</th>
                    <th>Created</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tickets as $ticket)
                    <tr>
                        <td>{{ $ticket->id }}</td>
                        <td>{{ $ticket->customer->name ?? 'N/A' }}</td>
                        <td>{{ \Illuminate\Support\Str::limit($ticket->title, 30) }}</td>
                        <td class="description">{{ \Illuminate\Support\Str::limit($ticket->description, 50) }}</td>
                        <td class="status-{{ $ticket->status }}">
                            {{ ucfirst(str_replace('_', ' ', $ticket->status)) }}
                        </td>
                        <td class="priority-{{ $ticket->priority }}">
                            {{ ucfirst($ticket->priority) }}
                        </td>
                        <td>{{ $ticket->assignedUser->name ?? 'Unassigned' }}</td>
                        <td>{{ $ticket->created_at->format('M j, Y') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">
            <p>No tickets found matching the specified criteria.</p>
        </div>
    @endif

    <div class="footer">
        <p>© {{ date('Y') }} ClientConnect CRM. This report is confidential and intended for internal use only.</p>
        <p>Page 1 of 1 | Generated at {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
